kill PHP server and stunnel after script is terminated

diff --git a/serveit b/serveit
--- a/serveit
+++ b/serveit
@@ -33,16 +33,34 @@ cat $CERT_FOLDER/$1-key.pem $CERT_FOLDER/$1-cert.pem > $CERT_FOLDER/$1-bundle.pe
 chmod 600 $CERT_FOLDER/$1-bundle.pem $CERT_FOLDER/$1-key.pem $CERT_FOLDER/$1-cert.pem
 
 # add domain to /etc/hosts
-sudo -E -- sh -c "echo '# added by serveit\n127.0.0.1 $1' >> /etc/hosts"
+echo "# added by serveit" >> /etc/hosts
+echo "127.0.0.1 $1" >> /etc/hosts
 
 # start PHP built in server
 php -S $1:$2 &
 
 # start stunnel
-sudo stunnel3 -f -d $3 -r $2 -p $CERT_FOLDER/$1-bundle.pem
+stunnel3 -f -d $3 -r $2 -p $CERT_FOLDER/$1-bundle.pem &
 
-# remove domain from hosts
-sudo sed -i -e "/# added by serveit/,/127.0.0.1 $1/d" /etc/hosts
+sleep 1
+echo ""
+echo "## Your local SSL site is now available at https://$1:$3"
 
-# remove certificates
-rm -f $CERT_FOLDER/$1-bundle.pem $CERT_FOLDER/$1-key.pem $CERT_FOLDER/$1-cert.pem
+# function to stop both servers
+cleanup() {
+    echo ""
+    echo "Removing /etc/hosts entry..."
+    sudo sed -i -e "/# added by serveit/,/127.0.0.1 $1/d" /etc/hosts
+
+    echo "Killing PHP and stunnel"
+    sudo kill $(jobs -p)
+
+    echo ""
+    echo "Killed servers."
+}
+
+# trap Ctrl+C signal and call cleanup function
+trap cleanup INT
+
+# wait for both servers to finish
+wait
